name: Build OGX-Mini

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependancies
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Get Pico SDK
        run: git clone --branch 2.1.0 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Create Build Folder
        run: |
          mkdir build
          mkdir output

# PI_PICO
# PI_PICO2
# PI_PICOW
# PI_PICO2W
# RP2040_ZERO
# ADAFRUIT_FEATHER
# ESP32_BLUEPAD32_I2C
# ESP32_BLUERETRO_I2C
# EXTERNAL_4CH_I2C

      - name: Build OGX-Mini - RP2040_ZERO
        run: |
          cd ${{ github.workspace }}/build
          rm -fr ./*
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DCMAKE_BUILD_TYPE=Release -DOGXM_BOARD=RP2040_ZERO -DMAX_GAMEPADS=1 ../Firmware/RP2040 
          cmake --build .
        #  cp ${{ github.workspace }}/build/picostation_pico1.uf2 ${{ github.workspace }}/output/picostation_pico1.uf2

      - name: List Files
        run: ls ${{ github.workspace }}/build

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: latest
          draft: true
          files: |
            ${{ github.workspace }}/output/*.uf2

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/output/*.uf2
